SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2

# Player's turn speed:
PLAYER_TURN_SPEED = 300

# Moving
PLAYER_SPEED = 200
PLAYER_ACCELERATION = 400
PLAYER_FRICTION = 0.98
PLAYER_MAX_SPEED = 450

# Asteroid constants:
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Scoring
SCORE_SMALL_ASTEROID = 100
SCORE_MEDIUM_ASTEROID = 50
SCORE_LARGE_ASTEROID = 20

# Shooting constants:
SHOT_RADIUS = 5

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

WEAPON_SINGLE = "SINGLE"
WEAPON_SPREAD = "SPREAD"
WEAPON_RAPID = "RAPID"

WEAPON_COLOR_SINGLE = (255, 255, 255)
WEAPON_COLOR_SPREAD = (0, 255, 0)
WEAPON_COLOR_RAPID = (255, 0, 0)

# Player hitbox tuning
PLAYER_HITBOX_SCALE = 0.9

# Player lives
PLAYER_LIVES = 3
PLAYER_RESPAWN_DELAY_SECONDS = 1.0  # pause before reactivating
PLAYER_RESPAWN_INVULNERABLE_SECONDS = 2.0

# Optional background
BACKGROUND_IMAGE_PATH = "background.png"  # place image in project root
